### ISSUE TITLE
Handling REST API error messages/status

### ISSUE THREAD

**Issue by pdonorio** [pdonorio/restangulask#12]
Following directives that can be found in EUDAT-B2STAGE/http-api-base#7

we must change [this method error callback](https://github.com/pdonorio/restangulask/blob/master/vanilla/jscode/commons/common.api.js#L72)

**Comment by mdantonio** [comment]
This issue is already solved?

**Comment by pdonorio** [comment]
I guess so. We did forgetting that it was inside an issue
