### ISSUE TITLE
Move backend common code in a common dir

### ISSUE THREAD

**Issue by pdonorio** [pdonorio/restangulask#22]
And then serve that dir inside `felask` frontend package with docker volumes

**Comment by pdonorio** [comment]
Also create a common format for endpoint response between frontend and backend

**Comment by pdonorio** [comment]
Also the secret creation must be accorded. 
Probably by running a container on a shared folder to create a common file.

**Comment by pdonorio** [comment]
What to move
- [x] html codes
- [x] meta package
- [x] defaults for users, roles and authentications on tests
- [x] logging

**Comment by pdonorio** [comment]
@mdantonio do you mind checking if you had calls to `meta` and `htmlcodes`.

You will find them in `commons.meta` and `commons.htmlcodes` now.

**Comment by mdantonio** [comment]
All verified

**Comment by pdonorio** [comment]
Moved all inside common.

We must:
- [x] use logging in every project with `from commons.logs import get_logger`
- [x] check where we use `confs.config` which is relative to the project now

This actions has to be done inside master and branches
