### ISSUE TITLE
Vanilla refactoring

### ISSUE THREAD

**Issue by mdantonio** [pdonorio/restangulask#32]
To simply both the development and the use of restangulask, we should migrate the vanilla directory from this repository to a separate repo.

Doing this we create an homology between backend and frontend

A custom project will use/clone/branch/fork the "vanilla repo" by including both backend and frontend as subfolder (as now work for backend only)

This involves a refactoring of restangulask code:
- vanilla directory is migrated to another repo (with the exclusion of jscode/[app/routes/common] that should remain in restangulask (*) )
- the do script follows the vanilla dir in the separate repository
- containers/docker_compose is split into backend/containers/backend_compose and frontend/containers/frontend_compose
- containers/custom is moved in new_vanilla_repo/containers and will use the base-containers in backend and frontend

(*) common js dir may be mounted via docker-compose? apps.js and routes.js could be moved into common (just to simplify)

**Comment by pdonorio** [comment]
This cannot be completed if we don't do #33 first

**Comment by pdonorio** [comment]
> containers/docker_compose is split into backend/containers/backend_compose and frontend/containers/frontend_compose

@mdantonio Shouldn't we start with this point already inside #33?

> the do script follows the vanilla dir in the separate repository

Uhm, why? I can't recall at the moment the reason we decided for this.
There should probably be a do base and a do custom.

**Comment by mdantonio** [comment]
> Shouldn't we start with this point already inside #33?

Yes we should... but we can? We could try to merge everything tomorrow. If not tomorrow we have to delay to late August

> Uhm, why? I can't recall at the moment the reason we decided for this.

After the refactoring we will have 3 repository: backend, frontend and vanilla

```
[backend]            [frontend]
     |__________________|
               |
           [vanilla]

```

We cannot put the do command in backend neither in frontend, since it is generic and not specific for a single layer

But this is the some problem of the common dir, now in backend.

To solve such problems we should add a fourth repository: backend, frontend, base and vanilla

```
[backend]            [frontend]
     |__________________|
               |
             [base]
               |
           [vanilla]

```

But i really think that we should avoid to make it too complicated by adding one more repository... So we could just leave the common dir in backend.

If we want the do command in the main dir, so this command should be in vanilla repository

Otherwise we can move it to the common dir in backend, and call it as backend/common/do.py

Otherwise we can move it to the common dir in backend and put a wrapper in vanilla

**Comment by pdonorio** [comment]
> To solve such problems we should add a fourth repository: backend, frontend, base and vanilla

I've been already working what you call `base` as `template` (even if only for the backend for now, but I don't see any problem in adding also the frontend).

The template repo should contain the base vanilla examples, starting with the do command.
How about that?

**Comment by mdantonio** [comment]
What you describe is a single repository (you can call it as you wish: base, template, vanilla... but if it contains both common dir and vanilla templates is ONE repository).
Two repositories mean a base repository (containing common dir and do command and whatever else in common among other repositories and using repositories backend and frontend) and a vanilla (containing vanilla templates, to be forked/branched to implement custom stuffs) who uses the base repository.

Is a more complicated architecture and still not solves all problems (e.g. if do command is in the base repository it will no be in the main dir)

**Comment by pdonorio** [comment]
You'll have to explain this to me face to face then, because I don't understand why we should have both a base and a template when we end up forking the template anyway. 

Buon appetito!

**Comment by pdonorio** [comment]
TO DO:
- [x] Create a new repo (`RAPyDo`?) for implementing the template
- [x] Implement load of 3 compose files (backend, frontend, and debug or dev or prod)

Note: `vanilla` directory is probably going to be the root directory of the new repo...

**Comment by mdantonio** [comment]
The refactoring is quite complete, we just have to fix some minor issues:
- new do command is now in backend repo -> we have to add a wrapper in rapydo
- two customizable files (framework.json and content.json) are in frontend/config/angularjs

**Comment by pdonorio** [comment]
What is the current status based on the TODO list above?

**Comment by mdantonio** [comment]
> Implement load of 3 compose files (backend, frontend, and debug or dev or prod)

It is implemented but it's only  working in the old do command because the new do command is not finished yet... but the task here can be checked as completed.

Other points are still missing (add examples, write a do command wrapper and move away the two json files from the frontend repository)

**Comment by pdonorio** [comment]
Ok so recap of missing things:
- [x] move away the two json files from the frontend repository
- write examples which will be linked if current mode file does not exist (e.g. "debug file not found, see debug_example for writing one")
- check files in frontend/felask/static/ and frontend/felask/templates/ to remove frameworks (we only want google material)
- write the default file with all possible values
- migrated repositories to the new rapydo schema

**Comment by pdonorio** [comment]
This issue intersect with EUDAT-B2STAGE/http-api#15

**Comment by mdantonio** [comment]
You should migrate your applications to the new rapydo schema, to remove the global_json_config branch from the backend and back to develop on the same code (I'm keeping updated the global_json_config with your implementations on master, but this is time consuming also due to the potential conflicts and the inverted development schema (from master to branch instead of branch to master).

Since the remaining points can be mainly completed by yourself, i assign this issue to you also
