### ISSUE TITLE
Refactor ./do command to follow new running modes

### ISSUE THREAD

**Issue by pdonorio** [pdonorio/restangulask#33]
See EUDAT-B2STAGE/http-api-base#15

We should arrive to a point where we do:

``` bash
./do MYPROJECT DEBUG/DEVELOPMENT/PRODUCTION [restart/NUMBER_OF WORKERS]

e.g.
# Debug mode for eudat project with graceful restart
./do eudat DEBUG

# Debug mode for eudat project with hard restart
./do eudat DEBUG restart

# Development mode for telethon project with 2 celery worker
./do telethon DEVELOPMENT 2

# Production and stop any existing worker
./do template PRODUCTION 0


```

**Comment by pdonorio** [comment]
This is also the right issue to consider using python + docker-py for doing containers handling,

see #14

**Comment by pdonorio** [comment]
CI tests are not able to resolve or force resolutions.

This means that bower configuration should already provide resolutions before pushing changes.

**Comment by pdonorio** [comment]
If we use docker-py there is a good chance we could also import from docker-compose library python functions equivalent to docker-compose commands.

**Comment by pdonorio** [comment]
Another possible template:

``` bash
./do MYPROJECT MODE ACTION [SERVICE] [NUMBER_OF_WORKERS]
```

`MYPROJECT` is the name of the folder which implements debug, development and production modes with YAML files for docker-compose.

`MODE` is one of: debug, development, production

ACTIONs, like [start, stop, restart, graceful, logs, scale, remove, clean, command, open shell]

``` bash
./do MYPROJECT list_services
```

is the command that should list the services available inside the docker-compose files.

Things the `do` command should do
- [ ] use `argparse` to parse commands?
- [ ] if  we do not specify one of the mandatory command, we get the list the options available for that command
- [ ] inspect containers and errors via docker-py
- [ ] run tests
- [ ] let the developer user add custom commands to the listed ones (e.g. some python functions or code in  `vanilla/docommands/`)

**Comment by pdonorio** [comment]
Here I created an example of using the python docker compose library to call compose commands:
https://github.com/pdonorio/restapi-template/blob/master/notebooks/test_compose.py

**Comment by mdantonio** [comment]
I tried to test your example, but i found a huge problem on ubuntu 14.04

The problem is reported here:

https://github.com/docker/docker-py/issues/1054

The import of docker_compose fails due to an old version of urllib3

```
    from compose.cli.main import TopLevelCommand
  File "/usr/local/lib/python3.4/dist-packages/compose/cli/main.py", line 14, in <module>
    from . import errors
  File "/usr/local/lib/python3.4/dist-packages/compose/cli/errors.py", line 9, in <module>
    from docker.errors import APIError
  File "/usr/local/lib/python3.4/dist-packages/docker/__init__.py", line 20, in <module>
    from .client import Client, AutoVersionClient, from_env # flake8: noqa
  File "/usr/local/lib/python3.4/dist-packages/docker/client.py", line 25, in <module>
    from . import api
  File "/usr/local/lib/python3.4/dist-packages/docker/api/__init__.py", line 2, in <module>
    from .build import BuildApiMixin
  File "/usr/local/lib/python3.4/dist-packages/docker/api/build.py", line 9, in <module>
    from .. import utils
  File "/usr/local/lib/python3.4/dist-packages/docker/utils/__init__.py", line 1, in <module>
    from .utils import (
  File "/usr/local/lib/python3.4/dist-packages/docker/utils/utils.py", line 33, in <module>
    from .. import tls
  File "/usr/local/lib/python3.4/dist-packages/docker/tls.py", line 5, in <module>
    from .ssladapter import ssladapter
  File "/usr/local/lib/python3.4/dist-packages/docker/ssladapter/__init__.py", line 1, in <module>
    from .ssladapter import SSLAdapter # flake8: noqa
  File "/usr/local/lib/python3.4/dist-packages/docker/ssladapter/ssladapter.py", line 22, in <module>
    urllib3.connection.match_hostname = match_hostname
```

Version installed: 1.7.1.
Version required: 1.14

And here the huge problem, on ubuntu urllib3 cannot be upgraded because "owned by OS"

```
sudo pip3 install urllib3==1.14

Downloading/unpacking urllib3==1.14
  Downloading urllib3-1.14-py2.py3-none-any.whl (89kB): 89kB downloaded
Installing collected packages: urllib3
  Found existing installation: urllib3 1.7.1
    Not uninstalling urllib3 at /usr/lib/python3/dist-packages, owned by OS
Successfully installed urllib3
Cleaning up...
```

**Comment by pdonorio** [comment]
Remove docker compose and try to install it on python 3, e.g. using pip3

Il Lun 18 Lug 2016, 10:23 mdantonio notifications@github.com ha scritto:

**Comment by mdantonio** [comment]
docker-compose is already installed via pip:

```
pip3 freeze | grep docker

docker-compose==1.7.1
docker-py==1.8.1
dockerpty==0.4.1
```

**Comment by pdonorio** [comment]
Uhm. But how is this a problem related only to ubuntu 14? A specific urllib
version?

Il Lun 18 Lug 2016, 10:34 mdantonio notifications@github.com ha scritto:

**Comment by mdantonio** [comment]
> Uhm. But how is this a problem related only to ubuntu 14? A specific urllib
> version?

urllib is installed at version 1.7.1 (required 1.14) and cannot be upgraded because owned by OS (as described in the linked issue on docker-py repository)

**Comment by pdonorio** [comment]
I see. I can't make tests or checks right now. Try on Ubuntu 16 on
openstack in the meanwhile.

Il Lun 18 Lug 2016, 10:52 mdantonio notifications@github.com ha scritto:

**Comment by pdonorio** [comment]
You may also try with pip an older version of compose (1.7.0?)

**Comment by mdantonio** [comment]
> Try on Ubuntu 16 on openstack in the meanwhile.

With ubuntu 16 there is no problem (urllib is updated to an newer version)

> You may also try with pip an older version of compose (1.7.0?)

No difference, same error

An upgrade to ubuntu 16 is of course a solution... but in this case we are creating a do command with a very strong OS requirement

**Comment by mdantonio** [comment]
You can test the template of DO command with argument parser

`python do.py -h` for help

`python do.py` for list of projects (directories found in containers/custom)

```
python do.py
INFO: List of available projects as found in **containers/custom**
INFO:   - demo
INFO:   - telethon
```

`python do.py --project YOUR_PROJECT` for list of modes available in project (yml files found in containers/custom/YOUR_PROJECT)

```
python do.py --project telethon
INFO: You selected project: telethon
INFO: List of available modes in project **telethon**
INFO:   - debug
INFO:   - devel
INFO:   - production
```

`python do.py --project YOUR_PROJECT --mode YOUR_MODE` to select a mode in a project.

Other available options: 

--list (list of service found in yaml, to be implemented)
--service
--workers

The final output is a docker-compose command to be executed (not executed, due to python docker-compose problems as issued above)

docker-compose -f base.yml -f selectedProject.Mode.yml ACTION SERVICE WORKERS

es:

```
python do.py --project telethon --mode debug --action start --service graphdb
Command to be executed:
    docker-compose -f containers/custom/containers.yml -f containers/custom/telethon/debug.yml start graphdb
```

**Comment by pdonorio** [comment]
Ah, it's looking great! I'll take a look now on that bad ubuntu 14 issue.

**Comment by pdonorio** [comment]
I can't reproduce the problem with Docker:

``` bash
docker run -it ubuntu:14.04 bash

root@ddd46d5f77c5:/# apt-get update

root@ddd46d5f77c5:/# apt-get install -y python3-setuptools

root@ddd46d5f77c5:/# easy_install3 pip

root@ddd46d5f77c5:/# pip3 install docker-compose

root@ddd46d5f77c5:/# python3
Python 3.4.3 (default, Oct 14 2015, 20:28:29)
[GCC 4.8.4] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from compose.cli.main import TopLevelCommand
>>>

```

I don't get that urllib error. Maybe other things have to be done to enable the issue.

Anyway I read some interesting hack [here](https://github.com/docker/docker-py/issues/1054) if it could be helpful.

**Comment by mdantonio** [comment]
> Ah, it's looking great!

Well, so we are on the right way?

> Anyway I read some interesting hack here if it could be helpful

This is the issue that I linked in this issue above... are you trying to fooling me? :smile: 
None of the solution proposed in that issue works for me.

> I can't reproduce the problem with Docker [...] I don't get that urllib error. 
> Maybe other things have to be done to enable the issue.

Or maybe the ubuntu docker image is fixed anyway by forcing the library upgrade...

However we have to decide about this issue. I can upgrade my ubuntu to 16.04 and ignore the problem. When other users in future will have this problem we simply will explain that we require at least ubuntu 16... but this solution is a little drastic...
Otherwise  we can avoid the use of docker-compose library and directly execute docker compose commands from python. Or we could use the docker-compose when it works and directly execute commands otherwise:

```
try:
    import docker-compose
    use_library=True
except:
   from subprocess import call
   use_library=false

def exec_docker_compose(command):
    if use_library:
         ....
    else:
        call(command)

```

**Comment by pdonorio** [comment]
> Well, so we are on the right way?

We are! Much simpler, cleaner and also powerful thanks to python 

> are you trying to fooling me? 

oops. Lol! Not easy when you check things with the smartphone 📱 
So even changing the python path didn't work? 

> Or we could use the docker-compose when it works and directly execute commands otherwise

Ah, that is a great and pythonic solution. Since we will need a `requirements.txt` anyway, I'd go with plumbum. I will build a function to let that work good, next week. 

Also we have to keep in mind that people should be able to use the script with python 2,which comes already installed.

**Comment by mdantonio** [comment]
> I will build a function to let that work good, next week.

Ok, so i wait for such function. In the meanwhile i will implement things around it

> --list (list of service found in yaml, to be implemented)

How to implement this? Docker-compose is able to list services found in yaml? Or I have to create a yaml parser to list services?

**Comment by pdonorio** [comment]
> How to implement this?

I just created for you an example to use docker compose, see [this](https://github.com/pdonorio/restapi-template/blob/master/notebooks/test_compose.py#L64-L70).

**Comment by mdantonio** [comment]
This example doesn't work for me, it produces no output (I think the problem is in @contextlib.contextmanager)

However i think you can just move your tests/template into the [do.py](https://github.com/pdonorio/restangulask/blob/master/do.py)... let's integrate my arguments template with your docker-compose-commands template to obtain a real DO template

**Comment by pdonorio** [comment]
Ok.

But: we should use some very basic docker image from alpine to have the same environment to test the do command. It should have the python 3 + libs installed, and also the docker client and mount the docker socket from the engine on the host.

**Comment by mdantonio** [comment]
Actions to be implemented:

```
- check? [to verify if a blueprint is well-configured]
- init? [as in old do command]
- update? [as in old do command, update docker images and bower]
- bower [to install/update bower libs]
- start [start of a single service?]
- stop [stop of a single service?]
- restart [start/restart the whole stack]
- graceful [restart as implemented in the old do command]
- logs [view all logs or logs for a service]
- scale [to be coupled with num_worker, maybe it could become a single option...]
- remove
- clean
- command [to execute a single command on a container?]
- shell [open a shell in a container]
```

check, init and update should require no other options (only --project and --mode)

bower should take all text following the last option as bower options (e.g. "do --project P --mode D --action bower install the library that I like")

start and stop should require --service as mandatory

restart and graceful should not require --service (or it could be optional? A list of services?)

logs --service is optional

scale: could be removed and automatically set when --num_worker is applied

remove and clean: how these commands should work?

command: --service should be mandatory and all text following the last option should be used as command (e.g. "do --project P --mode D --service S --action command rm -rf")

shell: --service should be mandatory

**Comment by pdonorio** [comment]
> restart and graceful should not require --service (or it could be optional? A list of services?)

they make sense only if you do that action on all the services, to me

> scale: could be removed and automatically set when --num_worker is applied

agreed

> shell: --service should be mandatory

or should be `backend` the default service? also in other commands?

> remove and clean: how these commands should work?

"remove" is equivalent to compose `stop` + `rm`, 
while "clean" has now the dedicated compose command `down`:

``` bash
$ docker-compose down --help

Stops containers and removes containers, networks, volumes, and images
created by `up`.
```

Both should work only for all the services.

**Comment by mdantonio** [comment]
Implemented single actions, example of valid commands (to be tested):

```
$ do.py --project telethon --mode debug --action start --service backend
docker-compose -f containers/custom/containers.yml -f containers/custom/telethon/debug.yml start backend

$ do.py --project telethon --mode debug --workers 5 --service celery
docker-compose -f containers/custom/containers.yml -f containers/custom/telethon/debug.yml scale celery=5

$ do.py --project telethon --mode debug --action shell --service frontend
docker-compose -f containers/custom/containers.yml -f containers/custom/telethon/debug.yml exec frontend bash

$ do.py --project telethon --mode debug --action command --service frontend execute your own command
docker-compose -f containers/custom/containers.yml -f containers/custom/telethon/debug.yml exec frontend execute your own command

$ do.py --project telethon --mode debug --action bower install JustALibrary
docker-compose -f containers/custom/containers.yml -f containers/custom/telethon/debug.yml exec bower install JustALibrary

```

**Comment by mdantonio** [comment]
I implemented the option to define custom actions in vanilla.

now the do.py command uses a class (ImplementedActions) defined in do_actions.py to handle all default actions

The ImplementedActions can be extended by implementing a CustomActions class in vanilla/do_actions/**init**.py to add more actions (i.e. do_something methods)

Here an example:

Standard behaviour:

```
$ do.py --project myproject --mode debug
Available actions:
    ['bower', 'check', 'clean', 'command', 'graceful', 'init', 'logs', 'remove', 'restart', 'scale', 'shell', 'start', 'stop', 'update']
```

By adding the following class in vanilla/do_actions/__init __.py

```
from do_actions import ImplementedActions

class CustomActions(ImplementedActions):

    def do_acustomaction(project):
        print("Just a custom action on project: %s " % project)

```

I obtain this:

```
$ do.py --project myproject --mode debug
Available actions:
    ['acustomaction', 'bower', 'check', 'clean', 'command', 'graceful', 'init', 'logs', 'remove', 'restart', 'scale', 'shell', 'start', 'stop', 'update']

$ do.py --project myproject --mode debug --action acustomaction
Just a custom action on project: myproject
```

**Comment by pdonorio** [comment]
Wowowowow! 👍

**Comment by pdonorio** [comment]
We have to wait for #32 to create the separated docker-compose in backend and frontend to be imported (with `-f` option of docker-compose)

**Comment by pdonorio** [comment]
TO DO:
- implement adding of docker-compose files from vanilla implementation
- use plumbum to launch docker-compose if try/except does not import correctly urllib3 or other docker-compose libraries
- pull only custom selected service images (with option services as a list?)
- undockerized option

**Comment by pdonorio** [comment]
We should provide an option for using the project without docker. See [this comment](https://github.com/EUDAT-B2STAGE/http-api-base/issues/26#issuecomment-235252234).

**Comment by pdonorio** [comment]
This issue intersect with EUDAT-B2STAGE/http-api#15

**Comment by mdantonio** [comment]
We should add a "setup" option to configure/init a new project

Setup a new project means create several directories and files into the template (very annoying to do by hand)

containers/PROJECT/[debug|development|production].yml
js/PROJECT/[...].js
specs/PROJECT.json
templates/PROJECT

All could be copied from demo (or graphbased) template and/or could be created by an interactive mode

Do you need both backend and frontend?
Which authentication service do you need?
Init DB with default user?
Default user credentials?
Do you want seven perpendicular red lines drawn with red, geen and transparent ink?

**Comment by pdonorio** [comment]
I like it, and of course agree. 

Especially on the last question :P
